"""
SQLAlchemy ORM models for QR code generation and gatekeeper session management.
All models use explicit table names and indexes for query optimization.
"""
from sqlalchemy import Column, BigInteger, String, DateTime, Boolean, Index, text
from sqlalchemy.dialects.postgresql import UUID
from datetime import datetime

from src.core.database import Base


class QRLog(Base):
    """
    Tracks generated QR codes with cryptographic signature hashes.
    
    Purpose:
        - Prevent QR code replay attacks
        - Enforce time-based expiration
        - Audit trail for QR generation events
    
    Indexes:
        - qr_signature_hash: Unique index for O(1) signature verification lookups
        - expires_at: Index for efficient cleanup of expired QR codes
    """
    __tablename__ = "qr_logs"
    
    id = Column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for QR log entries"
    )
    
    qr_signature_hash = Column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="SHA-256 hash of the cryptographic signature for uniqueness verification"
    )
    
    venue_id = Column(
        String(100),
        nullable=False,
        comment="Identifier for the venue/location where QR was generated"
    )
    
    created_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        comment="Timestamp when QR code was generated"
    )
    
    expires_at = Column(
        DateTime,
        nullable=False,
        index=True,
        comment="Expiration timestamp for QR code validity window"
    )
    
    # Composite index for venue-based queries with expiration filtering
    __table_args__ = (
        Index('idx_venue_expires', 'venue_id', 'expires_at'),
    )
    
    def __repr__(self):
        return f"<QRLog(id={self.id}, venue_id={self.venue_id}, expires_at={self.expires_at})>"


class GatekeeperSession(Base):
    """
    Manages ephemeral session tokens for form access control.
    
    Purpose:
        - Issue single-use session tokens after QR verification
        - Prevent token reuse attacks
        - Track device fingerprints for security auditing
    
    Indexes:
        - session_token: Unique UUID index for O(1) token validation
        - expires_at: Index for efficient cleanup of expired sessions
    """
    __tablename__ = "gatekeeper_sessions"
    
    id = Column(
        BigInteger,
        primary_key=True,
        autoincrement=True,
        comment="Primary key for gatekeeper session entries"
    )
    
    session_token = Column(
        UUID(as_uuid=True),
        unique=True,
        nullable=False,
        server_default=text("gen_random_uuid()"),
        comment="Cryptographically secure UUID v4 token generated by PostgreSQL"
    )
    
    device_fingerprint = Column(
        String(255),
        nullable=False,
        comment="Browser/device fingerprint hash for security tracking"
    )
    
    qr_signature_hash = Column(
        String(255),
        nullable=True,
        comment="SHA-256 hash of QR signature to prevent same QR being scanned twice on same device"
    )
    
    is_used = Column(
        Boolean,
        nullable=False,
        default=False,
        comment="Flag to prevent token reuse (single-use enforcement)"
    )
    
    created_at = Column(
        DateTime,
        nullable=False,
        default=datetime.utcnow,
        comment="Timestamp when session token was created"
    )
    
    expires_at = Column(
        DateTime,
        nullable=False,
        index=True,
        comment="Expiration timestamp for session validity window"
    )
    
    # Composite indexes for security queries
    __table_args__ = (
        Index('idx_fingerprint_created', 'device_fingerprint', 'created_at'),
        Index('idx_qr_device_duplicate', 'qr_signature_hash', 'device_fingerprint'),
    )
    
    def __repr__(self):
        return f"<GatekeeperSession(id={self.id}, token={self.session_token}, is_used={self.is_used})>"
