import { CallInButton } from "./CallInButton";
import { StatusBadge } from "../shared/components/StatusBadge";
import { Icon } from "../shared/components/Icon";
import { avatarGradient, initials } from "../shared/avatar";
import type { Case } from "../shared/types";

function formatTime(iso?: string): string {
  if (!iso) return "";
  return new Date(iso).toLocaleTimeString([], {
    hour: "numeric",
    minute: "2-digit",
  });
}

function Reference({ c }: { c: Case }) {
  if (c.entryType === "walkin") {
    return (
      <span className="ref ref--walkin" title="Walk-in token number">
        <span className="ref__icon">
          <Icon name="ticket" size={17} />
        </span>
        <span className="ref__meta">
          <span className="ref__kind">Token</span>
          <span className="ref__value">#{c.tokenNumber}</span>
        </span>
      </span>
    );
  }
  return (
    <span className="ref ref--appt" title="Booked appointment">
      <span className="ref__icon">
        <Icon name="clock" size={17} />
      </span>
      <span className="ref__meta">
        <span className="ref__kind">Appt</span>
        <span className="ref__value">{formatTime(c.appointmentTime)}</span>
      </span>
    </span>
  );
}

interface QueueTableProps {
  cases: Case[];
  onUpdated: (updated: Case) => void;
}

export function QueueTable({ cases, onUpdated }: QueueTableProps) {
  return (
    <div className="queue-list" role="list">
      <div className="queue-row queue-row--head" aria-hidden="true">
        <span>Reference</span>
        <span>Citizen &amp; grievance</span>
        <span>Status</span>
        <span className="queue-row__action-col">Action</span>
      </div>

      {cases.map((c, i) => (
        <div
          className="queue-row"
          role="listitem"
          key={c.id}
          style={{ animationDelay: `${Math.min(i, 8) * 45}ms` }}
        >
          <div className="queue-cell queue-cell--ref" data-label="Reference">
            <Reference c={c} />
          </div>

          <div className="queue-cell queue-cell--main" data-label="Citizen">
            <span
              className="q-avatar"
              style={{ background: avatarGradient(c.citizenName) }}
              aria-hidden="true"
            >
              {initials(c.citizenName)}
            </span>
            <div className="q-main__text">
              <div className="q-name-row">
                <span className="citizen-name">{c.citizenName}</span>
                <span
                  className="ai-tag"
                  title="Summary generated by AI — review before acting"
                >
                  <Icon name="sparkles" size={11} /> AI
                </span>
              </div>
              <span className="citizen-summary">{c.summary}</span>
            </div>
          </div>

          <div className="queue-cell queue-cell--status" data-label="Status">
            <StatusBadge status={c.status} />
          </div>

          <div className="queue-cell queue-cell--action" data-label="Action">
            <CallInButton caseRecord={c} onUpdated={onUpdated} />
          </div>
        </div>
      ))}
    </div>
  );
}
